"""create import request tables

Revision ID: 1c27b594bf9f
Revises: 20260821_0003
Create Date: 2026-08-20 07:12:22.596307
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1c27b594bf9f'
down_revision: str | None = '20260821_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=False),
    sa.Column('rows_detected', sa.Integer(), nullable=False),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('request_date', sa.String(), nullable=True),
    sa.Column('used_llm_fallback', sa.Boolean(), nullable=False),
    sa.Column('parser_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_requests_request_id'), 'import_requests', ['request_id'], unique=True)
    op.create_table('request_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['import_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_items_request_id'), 'request_items', ['request_id'], unique=False)
    op.create_table('request_source_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['request_items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['import_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_request_source_references_request_id'), 'request_source_references', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_source_references_request_id'), table_name='request_source_references')
    op.drop_table('request_source_references')
    op.drop_index(op.f('ix_request_items_request_id'), table_name='request_items')
    op.drop_table('request_items')
    op.drop_index(op.f('ix_import_requests_request_id'), table_name='import_requests')
    op.drop_table('import_requests')
    # ### end Alembic commands ###
