"""add item_number and shelf_life to request_items

Revision ID: f5aa70577161
Revises: 1c27b594bf9f
Create Date: 2026-08-20 10:18:06.100503
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'f5aa70577161'
down_revision: str | None = '1c27b594bf9f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows; the app-level default (empty string, matching
    # unit/notes) doesn't apply retroactively to rows already in the table.
    op.add_column(
        'request_items',
        sa.Column('item_number', sa.String(), nullable=False, server_default=''),
    )
    op.add_column(
        'request_items',
        sa.Column('shelf_life', sa.String(), nullable=False, server_default=''),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_items', 'shelf_life')
    op.drop_column('request_items', 'item_number')
    # ### end Alembic commands ###
