from app.api.schemas import (
    CategoryDemand,
    DemandTrendPoint,
    ErpMatch,
    ExtractedItem,
    HomeResponse,
    HomeStat,
    KpiCard,
    PartnerDetails,
    RecentImport,
    RecentRequest,
    RegionalDemand,
    RequestedItem,
    ReviewCounts,
    ReviewResponse,
    SourceInfo,
    SourceReference,
    SummaryItem,
    SummaryMetrics,
    SummaryResponse,
    TopRequestedItem,
    TrendsResponse,
)

REQUEST_ID = "SD-2024-0611"
SOURCE_FILE = "Sudan_EmergencyRequest_MSF_June2024.xlsx"


HOME_RESPONSE = HomeResponse(
    userName="Lea",
    organization="action medeor",
    currentDate="June 13, 2024",
    stats=[
        HomeStat(
            key="requests_processed",
            label="Requests Processed",
            value="47",
            sub="since January 2024",
        ),
        HomeStat(key="items_matched", label="Items Matched", value="612", sub="avg. 13 per request"),
        HomeStat(
            key="overall_match_rate",
            label="Overall Match Rate",
            value="91.4%",
            sub="across all requests",
        ),
        HomeStat(
            key="partner_organizations",
            label="Partner Organizations",
            value="11",
            sub="active in 2024",
        ),
        HomeStat(
            key="avg_processing_time",
            label="Avg. Processing Time",
            value="4.2 min",
            sub="upload to offer",
        ),
    ],
    recentRequests=[
        RecentRequest(
            id="SD-2024-0611",
            partner="MSF Sudan",
            region="East Sudan (Kassala)",
            date="Jun 10, 2024",
            items=8,
            matchRate=97,
            status="Offer sent",
        ),
        RecentRequest(
            id="UA-2024-0608",
            partner="ICRC Ukraine",
            region="Kharkiv Oblast",
            date="Jun 08, 2024",
            items=31,
            matchRate=89,
            status="Offer sent",
        ),
        RecentRequest(
            id="GZ-2024-0529",
            partner="WHO Gaza",
            region="Gaza City",
            date="May 29, 2024",
            items=22,
            matchRate=91,
            status="Offer sent",
        ),
        RecentRequest(
            id="CD-2024-0502",
            partner="IRC DRC",
            region="Kinshasa",
            date="May 02, 2024",
            items=8,
            matchRate=100,
            status="Offer sent",
        ),
        RecentRequest(
            id="YE-2024-0418",
            partner="Save the Children",
            region="Aden, Yemen",
            date="Apr 18, 2024",
            items=19,
            matchRate=84,
            status="Offer sent",
        ),
        RecentRequest(
            id="SO-2024-0410",
            partner="UNICEF Somalia",
            region="Mogadishu",
            date="Apr 10, 2024",
            items=12,
            matchRate=92,
            status="Offer sent",
        ),
    ],
)

RECENT_IMPORTS = [
    RecentImport(
        id=1,
        fileName="Sudan_EmergencyRequest_MSF_June2024.xlsx",
        partner="MSF Sudan",
        date="2024-06-10",
        items=14,
        type="xlsx",
    ),
    RecentImport(
        id=2,
        fileName="Ukraine_MedReq_Q2_2024.pdf",
        partner="ICRC Ukraine",
        date="2024-06-08",
        items=31,
        type="pdf",
    ),
    RecentImport(
        id=3,
        fileName="Gaza_SupplyList_May2024.xlsx",
        partner="WHO Gaza",
        date="2024-05-29",
        items=22,
        type="xlsx",
    ),
    RecentImport(
        id=4,
        fileName="DRC_Kinshasa_Apr2024.xlsx",
        partner="IRC DRC",
        date="2024-05-02",
        items=8,
        type="xlsx",
    ),
    RecentImport(
        id=5,
        fileName="Yemen_Aden_MedList_Apr2024.xls",
        partner="Save the Children",
        date="2024-04-18",
        items=19,
        type="xls",
    ),
]

PARTNER_DETAILS = PartnerDetails(
    partner="MSF Sudan",
    region="East Sudan (Kassala)",
    requestId=REQUEST_ID,
    contact="Dr. Amira Hassan",
    confirmed=False,
    requestDate="June 10, 2024",
    sourceFile=SOURCE_FILE,
)

EXTRACTED_ITEMS = [
    ExtractedItem(
        id=1,
        name="Amoxicillin 500mg Capsules",
        quantity=2000,
        unit="caps",
        notes="Blister pack preferred",
        priority="critical",
        confidence=94,
        status="verified",
    ),
    ExtractedItem(
        id=2,
        name="Paracetamol 500mg Tablets",
        quantity=5000,
        unit="tabs",
        notes="Generic acceptable",
        priority="high",
        confidence=97,
        status="verified",
    ),
    ExtractedItem(
        id=3,
        name="ORS Sachets (WHO formula)",
        quantity=None,
        unit="sachets",
        notes="Quantity illegible in scan - oral rehydration salts",
        priority="high",
        confidence=41,
        status="missing",
    ),
    ExtractedItem(
        id=4,
        name="Sodium Chloride 0.9% IV 500ml",
        quantity=200,
        unit="bags",
        notes="Must be sterile",
        priority="critical",
        confidence=91,
        status="verified",
    ),
    ExtractedItem(
        id=5,
        name="Wound Dressing 10x10cm",
        quantity=1000,
        unit="pcs",
        notes="Non-adhesive sterile preferred",
        priority="medium",
        confidence=67,
        status="needs_review",
    ),
    ExtractedItem(
        id=6,
        name="Morphine HCl 10mg/ml Injection",
        quantity=50,
        unit="vials",
        notes="Controlled substance - special approval req.",
        priority="critical",
        confidence=89,
        status="verified",
    ),
    ExtractedItem(
        id=7,
        name="Surgical Gloves Size M (Latex-free)",
        quantity=500,
        unit="pairs",
        notes="Sterile, individually wrapped",
        priority="medium",
        confidence=82,
        status="verified",
    ),
    ExtractedItem(
        id=8,
        name="Diazepam 5mg Tablets",
        quantity=200,
        unit="tabs",
        notes="For seizure management - schedule IV",
        priority="high",
        confidence=55,
        status="low_confidence",
    ),
]

SOURCE_REFERENCES = [
    SourceReference(
        itemId=1,
        page=3,
        row=14,
        excerpt='"Amoxicillin 500mg caps [2000 pcs] - priority critical, blister pack preferred"',
    ),
    SourceReference(
        itemId=2,
        page=3,
        row=15,
        excerpt='"Paracetamol 500mg tablets [5000 pcs] - generic acceptable"',
    ),
    SourceReference(
        itemId=3,
        page=4,
        row=2,
        excerpt=(
            '"ORS sachets WHO formula [qty illegible] - oral rehydration, high priority" - '
            "item identified but quantity could not be read due to scan quality"
        ),
    ),
    SourceReference(
        itemId=4,
        page=4,
        row=5,
        excerpt='"NaCl 0.9% IV bags 500ml [200 bags] - sterile, critical priority"',
    ),
    SourceReference(
        itemId=5,
        page=4,
        row=8,
        excerpt='"Wound dressings 10x10 cm non-adhesive [1000 pcs] - sterile"',
    ),
    SourceReference(
        itemId=6,
        page=5,
        row=1,
        excerpt='"Morphine HCl 10mg/ml inj. [50 vials] - controlled substance, critical"',
    ),
    SourceReference(
        itemId=7,
        page=5,
        row=3,
        excerpt='"Surgical gloves size M latex-free sterile [500 pairs]"',
    ),
    SourceReference(
        itemId=8,
        page=5,
        row=6,
        excerpt='"Diazepam 5mg tabs [200 pcs] - schedule IV, seizure mgmt, high prio"',
    ),
]

REQUESTED_ITEMS = [
    RequestedItem(
        id=1, name="Amoxicillin 500mg Capsules", quantity=2000, unit="caps", priority="critical"
    ),
    RequestedItem(id=2, name="Paracetamol 500mg Tablets", quantity=5000, unit="tabs", priority="high"),
    RequestedItem(id=3, name="ORS Sachets (WHO formula)", quantity=500, unit="sachets", priority="high"),
    RequestedItem(
        id=4,
        name="Sodium Chloride 0.9% IV 500ml",
        quantity=200,
        unit="bags",
        priority="critical",
    ),
    RequestedItem(id=5, name="Wound Dressing 10x10cm", quantity=1000, unit="pcs", priority="medium"),
    RequestedItem(
        id=6,
        name="Morphine HCl 10mg/ml Injection",
        quantity=50,
        unit="vials",
        priority="critical",
    ),
    RequestedItem(
        id=7,
        name="Surgical Gloves Size M (Latex-free)",
        quantity=500,
        unit="pairs",
        priority="medium",
    ),
    RequestedItem(id=8, name="Diazepam 5mg Tablets", quantity=200, unit="tabs", priority="high"),
]

ERP_MATCHES = {
    1: [
        ErpMatch(
            id="erp-001",
            name="Amoxicillin 500mg Capsules",
            sku="AM500-CAP-1000",
            manufacturer="GlobalPharma GmbH",
            score=97,
            stock=4200,
            unit="caps",
        ),
        ErpMatch(
            id="erp-002",
            name="Amoxicillin 500mg Caps (500-ct)",
            sku="AM500-CAP-500",
            manufacturer="MedSource GmbH",
            score=94,
            stock=8000,
            unit="caps",
        ),
        ErpMatch(
            id="erp-003",
            name="Amoxicillin Trihydrate 500mg",
            sku="AMTH-500-CAP",
            manufacturer="PharmaCorp AG",
            score=81,
            stock=1500,
            unit="caps",
        ),
        ErpMatch(
            id="erp-004",
            name="Amoxicillin 500mg (Bulk, 5000-ct)",
            sku="AM500-BULK",
            manufacturer="BulkMed Inc.",
            score=76,
            stock=20000,
            unit="caps",
        ),
        ErpMatch(
            id="erp-004b",
            name="Co-Amoxiclav 500/125mg Capsules",
            sku="COAMOX-500-CAP",
            manufacturer="EuroPharma AG",
            score=61,
            stock=3200,
            unit="caps",
        ),
        ErpMatch(
            id="erp-004c",
            name="Ampicillin 500mg Capsules",
            sku="AMP-500-CAP",
            manufacturer="GenMed GmbH",
            score=54,
            stock=6000,
            unit="caps",
        ),
    ],
    2: [
        ErpMatch(
            id="erp-005",
            name="Paracetamol 500mg Tablets",
            sku="PC500-TAB-1000",
            manufacturer="EssentialMed GmbH",
            score=99,
            stock=25000,
            unit="tabs",
        ),
        ErpMatch(
            id="erp-006",
            name="Paracetamol 500mg Film-Coated",
            sku="PC500-FC-500",
            manufacturer="MedSource GmbH",
            score=95,
            stock=12000,
            unit="tabs",
        ),
        ErpMatch(
            id="erp-007",
            name="Acetaminophen 500mg Tablets",
            sku="ACET-500-TAB",
            manufacturer="USPharm Corp.",
            score=88,
            stock=5000,
            unit="tabs",
        ),
        ErpMatch(
            id="erp-007b",
            name="Paracetamol 500mg Suppositories",
            sku="PC500-SUPP-10",
            manufacturer="AltRoute GmbH",
            score=72,
            stock=3000,
            unit="pcs",
        ),
        ErpMatch(
            id="erp-007c",
            name="Paracetamol 250mg Tablets (x2)",
            sku="PC250-TAB-2000",
            manufacturer="EssentialMed GmbH",
            score=68,
            stock=18000,
            unit="tabs",
        ),
    ],
    3: [
        ErpMatch(
            id="erp-008",
            name="ORS Sachets WHO-Standard Formula",
            sku="ORS-WHO-SAC-100",
            manufacturer="WHO Supplier A",
            score=98,
            stock=2000,
            unit="sachets",
        ),
        ErpMatch(
            id="erp-009",
            name="ORS Sachets Glucose-Electrolyte Plus",
            sku="ORS-GE-PLUS-50",
            manufacturer="NutriMed GmbH",
            score=84,
            stock=800,
            unit="sachets",
        ),
        ErpMatch(
            id="erp-010",
            name="Oral Rehydration Salts (Generic)",
            sku="ORS-GEN-200",
            manufacturer="GenericMed Ltd.",
            score=72,
            stock=3000,
            unit="sachets",
        ),
    ],
    4: [
        ErpMatch(
            id="erp-011",
            name="Sodium Chloride 0.9% IV Bag 500ml",
            sku="NaCl-0.9-500-PP",
            manufacturer="InfuMed GmbH",
            score=99,
            stock=1200,
            unit="bags",
        ),
        ErpMatch(
            id="erp-012",
            name="Saline 0.9% Infusion 500ml",
            sku="SAL-0.9-500",
            manufacturer="Fresenius Kabi",
            score=97,
            stock=2400,
            unit="bags",
        ),
        ErpMatch(
            id="erp-013",
            name="NaCl 0.9% Infusion 500ml (Glass)",
            sku="NaCl-0.9-500-GL",
            manufacturer="GlassPharma AG",
            score=90,
            stock=350,
            unit="bags",
            lowStock=True,
        ),
    ],
    5: [
        ErpMatch(
            id="erp-014",
            name="Non-Adhesive Wound Dressing 10x10cm",
            sku="WD-10X10-NA-ST",
            manufacturer="MedTex GmbH",
            score=91,
            stock=5000,
            unit="pcs",
        ),
        ErpMatch(
            id="erp-015",
            name="Sterile Gauze Dressing 10x10cm",
            sku="WD-10X10-S-100",
            manufacturer="BandageCo Ltd.",
            score=85,
            stock=8000,
            unit="pcs",
        ),
        ErpMatch(
            id="erp-016",
            name="Polyurethane Foam Dressing 10x10cm",
            sku="WD-FOAM-10-50",
            manufacturer="FoamMed AG",
            score=72,
            stock=2000,
            unit="pcs",
        ),
    ],
    6: [
        ErpMatch(
            id="erp-017",
            name="Morphine Sulfate 10mg/ml Injection",
            sku="MORPH-SO4-10-INJ",
            manufacturer="ControlMed GmbH",
            score=96,
            stock=200,
            unit="vials",
            lowStock=True,
        ),
        ErpMatch(
            id="erp-018",
            name="Morphine HCl 10mg/ml Ampoules",
            sku="MORPH-HCL-10-INJ",
            manufacturer="AmpoulePharm AG",
            score=94,
            stock=150,
            unit="vials",
            lowStock=True,
        ),
    ],
    7: [
        ErpMatch(
            id="erp-019",
            name="Surgical Gloves M Latex-Free (Sterile)",
            sku="GLOVE-NIT-M-ST-50",
            manufacturer="SafeHands GmbH",
            score=97,
            stock=3000,
            unit="pairs",
        ),
        ErpMatch(
            id="erp-020",
            name="Exam Gloves M Latex-Free (Non-Sterile)",
            sku="GLOVE-NIT-M-NS",
            manufacturer="MedGlove Corp.",
            score=78,
            stock=9000,
            unit="pairs",
        ),
        ErpMatch(
            id="erp-021",
            name="Surgical Gloves M (Natural Latex)",
            sku="GLOVE-LAT-M-100",
            manufacturer="LatexCo Ltd.",
            score=62,
            stock=6000,
            unit="pairs",
        ),
    ],
    8: [
        ErpMatch(
            id="erp-022",
            name="Diazepam 5mg Tablets",
            sku="DIAZ-5MG-TAB-100",
            manufacturer="ControlPharma AG",
            score=98,
            stock=2500,
            unit="tabs",
        ),
        ErpMatch(
            id="erp-023",
            name="Diazepam 5mg Tablets (Bulk 1000-ct)",
            sku="DIAZ-5MG-BULK-1K",
            manufacturer="BulkPharma GmbH",
            score=92,
            stock=10000,
            unit="tabs",
        ),
    ],
}

SUMMARY_ITEMS = [
    SummaryItem(
        id=1,
        requested="Amoxicillin 500mg Capsules",
        erpProduct="Amoxicillin 500mg Capsules (1000-ct)",
        sku="AM500-CAP-1000",
        quantity=2000,
        unit="caps",
        packageSize="1000-ct blister",
        matchScore=97,
        stock="In Stock",
        pricePerUnit=0.08,
    ),
    SummaryItem(
        id=2,
        requested="Paracetamol 500mg Tablets",
        erpProduct="Paracetamol 500mg Tablets",
        sku="PC500-TAB-1000",
        quantity=5000,
        unit="tabs",
        packageSize="1000-ct blister",
        matchScore=99,
        stock="In Stock",
        pricePerUnit=0.03,
    ),
    SummaryItem(
        id=3,
        requested="ORS Sachets (WHO formula)",
        erpProduct="ORS Sachets WHO-Standard Formula",
        sku="ORS-WHO-SAC-100",
        quantity=500,
        unit="sachets",
        packageSize="100/carton",
        matchScore=98,
        stock="In Stock",
        pricePerUnit=0.45,
    ),
    SummaryItem(
        id=4,
        requested="Sodium Chloride 0.9% IV 500ml",
        erpProduct="Sodium Chloride 0.9% IV Bag 500ml",
        sku="NaCl-0.9-500-PP",
        quantity=200,
        unit="bags",
        packageSize="Single 500ml bag",
        matchScore=99,
        stock="In Stock",
        pricePerUnit=1.20,
    ),
    SummaryItem(
        id=5,
        requested="Wound Dressing 10x10cm",
        erpProduct="Non-Adhesive Wound Dressing 10x10cm",
        sku="WD-10X10-NA-ST",
        quantity=1000,
        unit="pcs",
        packageSize="Sterile, indiv. wrapped",
        matchScore=91,
        stock="In Stock",
        pricePerUnit=0.28,
    ),
    SummaryItem(
        id=6,
        requested="Morphine HCl 10mg/ml Injection",
        erpProduct="Morphine Sulfate 10mg/ml Injection",
        sku="MORPH-SO4-10-INJ",
        quantity=50,
        unit="vials",
        packageSize="10ml vials, 5/pack",
        matchScore=96,
        stock="Limited",
        pricePerUnit=3.50,
    ),
    SummaryItem(
        id=7,
        requested="Surgical Gloves Size M (Latex-free)",
        erpProduct="Surgical Gloves M Latex-Free (Sterile)",
        sku="GLOVE-NIT-M-ST-50",
        quantity=500,
        unit="pairs",
        packageSize="50 indiv. pairs/box",
        matchScore=97,
        stock="In Stock",
        pricePerUnit=0.55,
    ),
    SummaryItem(
        id=8,
        requested="Diazepam 5mg Tablets",
        erpProduct="Diazepam 5mg Tablets",
        sku="DIAZ-5MG-TAB-100",
        quantity=200,
        unit="tabs",
        packageSize="100 tabs/blister",
        matchScore=98,
        stock="In Stock",
        pricePerUnit=0.12,
    ),
]

TREND_RESPONSE = TrendsResponse(
    asOf="Jun 13, 2024 - 09:41 UTC",
    kpis=[
        KpiCard(
            key="requests_processed",
            label="Requests Processed",
            value="47",
            delta="+12 vs H1 2023",
            up=True,
            sub="Jan-Jun 2024",
        ),
        KpiCard(
            key="items_matched",
            label="Items Matched",
            value="612",
            delta="+18%",
            up=True,
            sub="Across 47 requests",
        ),
        KpiCard(
            key="overall_match_rate",
            label="Overall Match Rate",
            value="91.4%",
            delta="+2.1% vs 2023",
            up=True,
            sub="Incl. manual corrections",
        ),
        KpiCard(
            key="partner_organizations",
            label="Partner Organizations",
            value="11",
            delta="+3 new in 2024",
            up=True,
            sub="Active requesting partners",
        ),
        KpiCard(
            key="items_flagged",
            label="Items Flagged for Review",
            value="23",
            delta="3.8% of total items",
            up=False,
            sub="Low confidence / ambiguous",
        ),
        KpiCard(
            key="demand_growth",
            label="Demand Growth (YTD)",
            value="+34%",
            delta="vs same period 2023",
            up=True,
            sub="Based on requested items",
        ),
    ],
    demandTrend=[
        DemandTrendPoint(month="Jan", antibiotics=4200, analgesics=6800, trauma=2100, ivFluids=3400),
        DemandTrendPoint(month="Feb", antibiotics=4800, analgesics=7200, trauma=2300, ivFluids=3100),
        DemandTrendPoint(month="Mar", antibiotics=5100, analgesics=7500, trauma=2600, ivFluids=3700),
        DemandTrendPoint(month="Apr", antibiotics=5800, analgesics=8100, trauma=3200, ivFluids=4200),
        DemandTrendPoint(month="May", antibiotics=6400, analgesics=8900, trauma=4100, ivFluids=4800),
        DemandTrendPoint(month="Jun", antibiotics=7200, analgesics=9400, trauma=5600, ivFluids=5500),
    ],
    regionalDemand=[
        RegionalDemand(region="Sudan", requests=14, items=187),
        RegionalDemand(region="Ukraine", requests=11, items=341),
        RegionalDemand(region="Gaza", requests=9, items=198),
        RegionalDemand(region="DRC", requests=6, items=78),
        RegionalDemand(region="Yemen", requests=4, items=76),
        RegionalDemand(region="Haiti", requests=2, items=41),
        RegionalDemand(region="Somalia", requests=1, items=12),
    ],
    categoryDemand=[
        CategoryDemand(name="Broad-Spectrum Antibiotics", items=24800, change=28, risk="high"),
        CategoryDemand(name="Essential Analgesics", items=19400, change=15, risk="medium"),
        CategoryDemand(name="Trauma & Wound Care", items=16200, change=41, risk="high"),
        CategoryDemand(name="IV Fluids & Electrolytes", items=14600, change=22, risk="medium"),
        CategoryDemand(name="Emergency Kits", items=8900, change=56, risk="critical"),
        CategoryDemand(name="Pediatric Medicine", items=6800, change=18, risk="medium"),
    ],
    topItems=[
        TopRequestedItem(name="Paracetamol 500mg Tablets", requests=38, totalQty=142000, trend=12),
        TopRequestedItem(name="Amoxicillin 500mg Capsules", requests=31, totalQty=98500, trend=28),
        TopRequestedItem(name="ORS Sachets (WHO formula)", requests=27, totalQty=54000, trend=8),
        TopRequestedItem(name="Sodium Chloride 0.9% IV 500ml", requests=24, totalQty=12400, trend=34),
        TopRequestedItem(name="Wound Dressings 10x10cm", requests=21, totalQty=67000, trend=41),
        TopRequestedItem(name="Surgical Gloves (Latex-free)", requests=19, totalQty=38500, trend=5),
    ],
)


def review_counts(items: list[ExtractedItem] | None = None) -> ReviewCounts:
    rows = items or EXTRACTED_ITEMS
    return ReviewCounts(
        total=len(rows),
        verified=sum(1 for item in rows if item.status == "verified"),
        needsReview=sum(1 for item in rows if item.status == "needs_review"),
        lowConfidence=sum(1 for item in rows if item.status == "low_confidence"),
        missing=sum(1 for item in rows if item.status == "missing"),
    )


def review_response() -> ReviewResponse:
    return ReviewResponse(
        requestId=REQUEST_ID,
        source=SourceInfo(
            fileName=SOURCE_FILE,
            rowsDetected=len(EXTRACTED_ITEMS),
            partner=PARTNER_DETAILS.partner,
        ),
        partner=PARTNER_DETAILS,
        items=EXTRACTED_ITEMS,
        sourceReferences=SOURCE_REFERENCES,
        counts=review_counts(),
    )


def summary_metrics() -> SummaryMetrics:
    total_value = sum(item.pricePerUnit * item.quantity for item in SUMMARY_ITEMS)
    return SummaryMetrics(
        totalLineItems=len(SUMMARY_ITEMS),
        highConfidenceMatches=sum(1 for item in SUMMARY_ITEMS if item.matchScore >= 90),
        averageMatchScore=round(
            sum(item.matchScore for item in SUMMARY_ITEMS) / len(SUMMARY_ITEMS)
        ),
        estimatedTotalValue=total_value,
    )


def summary_response() -> SummaryResponse:
    return SummaryResponse(
        requestId=REQUEST_ID,
        sourceFile=SOURCE_FILE,
        partner=PARTNER_DETAILS,
        items=SUMMARY_ITEMS,
        metrics=summary_metrics(),
    )

